version: '3'

services:
  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    command: fresh
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres